# Generated by Django 2.1.7 on 2022-02-07 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220207_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 7, 17, 3, 28, 91711)),
        ),
    ]
